In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print('Libraries loaded')

Libraries loaded

In [2]:
df = pd.read_csv('../data/raw/online_retail_II.csv', encoding = 'utf-8', low_memory = False)

In [3]:
print('Shape:', df.shape)

Shape: (1067371, 8)

In [4]:
print('Columns:', df.columns.tolist())

Columns: ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [5]:
df.head(3)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom

In [12]:
df = df.rename(columns={
    'Invoice' : 'invoice',
    'StockCode' : 'stock_code',
    'Description' : 'description',
    'Quantity' : 'quantity',
    'InvoiceDate' : 'invoice_date',
    'Price' : 'unit_price',
    'Customer ID' : 'customer_id',
    'Country' : 'country'
})

print('Renamed columns:', df.columns.tolist())

Renamed columns: ['invoice', 'stock_code', 'description', 'quantity', 'invoice_date', 'unit_price', 'customer_id', 'country']

In [14]:
df['invoice_date'] = pd.to_datetime(df['invoice_date'])
df['quantity'] = pd.to_numeric(df['quantity'], errors = 'coerce')
df['unit_price'] = pd.to_numeric(df['unit_price'], errors = 'coerce')
print(df.dtypes)
print('\nDate range:', df['invoice_date'].min(), 'to', df['invoice_date'].max())

invoice                    str
stock_code                 str
description                str
quantity                 int64
invoice_date    datetime64[us]
unit_price             float64
customer_id            float64
country                    str
dtype: object

Date range: 2009-12-01 07:45:00 to 2011-12-09 12:50:00

In [17]:
df['is_cancellation'] = df['invoice'].astype(str).str.startswith('C')

print('Cancellations:', df['is_cancellation'].sum())
print('Normal orders:', (~df['is_cancellation']).sum())

Cancellations: 19494
Normal orders: 1047877

In [18]:
df.head(10)

,invoice,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,is_cancellation
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,False
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom,False
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,False
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom,False

In [19]:
print('Rows before:', len(df))

Rows before: 1067371

In [21]:
print('Missing Customer ID:', df['customer_id'].isna().sum())

Missing Customer ID: 243007

In [23]:
df = df.dropna(subset = ['customer_id'])

In [24]:
df['customer_id'] = df['customer_id'].astype(int)
print('Rows after:', len(df))

Rows after: 824364

In [25]:
non_products = ['POST', 'DOT', 'M', 'BANK CHARGES', 'C2', 'S', 'AMAZONFEE', 'PADS']
print('Rows before:', len(df))
df = df[~df['stock_code'].astype(str).str.upper().isin(non_products)]
print('Rows after:', len(df))

Rows before: 824364
Rows after: 820898

In [26]:
print('Rows before:', len(df))
sales = df[(df['quantity'] > 0) & (df['unit_price'] > 0)].copy()
print('Sales rows:', len(sales))
print('Return rows removed:', len(df) - len(sales))

Rows before: 820898
Sales rows: 802684
Return rows removed: 18214

In [27]:
# Removed exact duplicates
sales = sales.drop_duplicates()
print('After dedup:', len(sales))
# Created revenue column
sales['line_revenue'] = sales['quantity'] * sales['unit_price']
# Cleaned text
sales['stock_code'] = sales['stock_code'].astype(str).str.strip().str.upper()
sales['description'] = sales['description'].astype(str).str.strip()
sales['country'] = sales['country'].astype(str).str.strip()
print('\nSample revenues:')
print(sales['line_revenue'].describe())

After dedup: 776629

Sample revenues:
count    776629.000000
mean         21.984083
std         225.927638
min           0.060000
25%           4.950000
50%          12.450000
75%          19.800000
max      168469.600000
Name: line_revenue, dtype: float64

In [28]:
# Creating tables
customers = (sales[['customer_id','country']]
.drop_duplicates('customer_id')
.reset_index(drop=True))

products = (sales.groupby('stock_code')['description']
.agg(lambda x: x.mode()[0])
.reset_index())

transactions = sales[[
'invoice','customer_id','stock_code',
'quantity','unit_price','invoice_date',
'line_revenue','is_cancellation'
]].reset_index(drop=True)
print('Customers:', customers.shape)
print('Products :', products.shape)
print('Transactions:', transactions.shape)

Customers: (5861, 2)
Products : (4625, 2)
Transactions: (776629, 8)

In [30]:
# Some checks
assert customers['customer_id'].is_unique, 'Duplicate customer IDs!'
assert products['stock_code'].is_unique, 'Duplicate stock codes!'
assert transactions['line_revenue'].min() > 0, 'Negative revenue in sales!'
print('All sanity checks passed!')
# Exporting as CSV
customers.to_csv('../data/processed/customers.csv', index=False)
products.to_csv('../data/processed/products.csv', index=False)
transactions.to_csv('../data/processed/transactions.csv', index=False)
print('Exported all 3 CSVs to data/processed/')

All sanity checks passed!
Exported all 3 CSVs to data/processed/

In [34]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
'postgresql://postgres:Aditya%40123@localhost:5432/retail_db'
)

customers.to_sql('customers', engine, if_exists='append', index=False)
products.to_sql('products', engine, if_exists='append', index=False)
transactions.to_sql('transactions', engine, if_exists='append', index=False,
chunksize=10000) # chunk for large tables
print('All 3 tables loaded into PostgreSQL!')

All 3 tables loaded into PostgreSQL!